export bytes_to_samples

"""
Return bytes to samples dict
"""
function bytes_to_samples()

    
    Dict{String, Int32}(
        "TraceNumWithinLine"              =>  1  -1,
        "TraceNumWithinFile"              =>  5  -1,
        "FieldRecord"                     =>  9  -1,
        "TraceNumber"                     =>  13 -1,
        "EnergySourcePoint"               =>  17 -1,
        "CDP"                             =>  21 -1,
        "CDPTrace"                        =>  25 -1,
        "TraceIDCode"                     =>  29 -1,
        "NSummedTraces"                   =>  31 -1,
        "NStackedTraces"                  =>  33 -1,
        "DataUse"                         =>  35 -1,
        "Offset"                          =>  37 -1,
        "RecGroupElevation"               =>  41 -1,
        "SourceSurfaceElevation"          =>  45 -1,
        "SourceDepth"                     =>  49 -1,
        "RecDatumElevation"               =>  53 -1,
        "SourceDatumElevation"            =>  57 -1,
        "SourceWaterDepth"                =>  61 -1,
        "GroupWaterDepth"                 =>  65 -1,
        "ElevationScalar"                 =>  69 -1,
        "RecSourceScalar"                 =>  71 -1,
        "SourceX"                         =>  73 -1,
        "SourceY"                         =>  77 -1,
        "GroupX"                          =>  81 -1,
        "GroupY"                          =>  85 -1,
        "CoordUnits"                      =>  89 -1,
        "WeatheringVelocity"              =>  91 -1,
        "SubWeatheringVelocity"           =>  93 -1,
        "UpholeTimeSource"                =>  95 -1,
        "UpholeTimeGroup"                 =>  97 -1,
        "StaticCorrectionSource"          =>  99 -1,
        "StaticCorrectionGroup"           =>  101-1,
        "TotalStaticApplied"              =>  103-1,
        "LagTimeA"                        =>  105-1,
        "LagTimeB"                        =>  107-1,
        "DelayRecordingTime"              =>  109-1,
        "MuteTimeStart"                   =>  111-1,
        "MuteTimeEnd"                     =>  113-1,
        "ns"                              =>  115-1,
        "dt"                              =>  117-1,
        "GainType"                        =>  119-1,
        "InstrumentGainConstant"          =>  121-1,
        "InstrumntInitialGain"            =>  123-1,
        "Correlated"                      =>  125-1,
        "SweepFrequencyStart"             =>  127-1,
        "SweepFrequencyEnd"               =>  129-1,
        "SweepLength"                     =>  131-1,
        "SweepType"                       =>  133-1,
        "SweepTraceTaperLengthStart"      =>  135-1,
        "SweepTraceTaperLengthEnd"        =>  137-1,
        "TaperType"                       =>  139-1,
        "AliasFilterFrequency"            =>  141-1,
        "AliasFilterSlope"                =>  143-1,
        "NotchFilterFrequency"            =>  145-1,
        "NotchFilterSlope"                =>  147-1,
        "LowCutFrequency"                 =>  149-1,
        "HighCutFrequency"                =>  151-1,
        "LowCutSlope"                     =>  153-1,
        "HighCutSlope"                    =>  155-1,
        "Year"                            =>  157-1,
        "DayOfYear"                       =>  159-1,
        "HourOfDay"                       =>  161-1,
        "MinuteOfHour"                    =>  163-1,
        "SecondOfMinute"                  =>  165-1,
        "TimeCode"                        =>  167-1,
        "TraceWeightingFactor"            =>  169-1,
        "GeophoneGroupNumberRoll"         =>  171-1,
        "GeophoneGroupNumberTraceStart"   =>  173-1,
        "GeophoneGroupNumberTraceEnd"     =>  175-1,
        "GapSize"                         =>  177-1,
        "OverTravel"                      =>  179-1,
        "CDPX"                            =>  181-1,
        "CDPY"                            =>  185-1,
        "Inline3D"                        =>  189-1,
        "Crossline3D"                     =>  193-1,
        "ShotPoint"                       =>  197-1,
        "ShotPointScalar"                 =>  201-1,
        "TraceValueMeasurmentUnit"        =>  203-1,
        "TransductionConstnatMantissa"    =>  205-1,
        "TransductionConstantPower"       =>  209-1,
        "TransductionUnit"                =>  211-1,
        "TraceIdentifier"                 =>  213-1,
        "ScalarTraceHeader"               =>  215-1,
        "SourceType"                      =>  217-1,
        "SourceEnergyDirectionMantissa"   =>  219-1,
        "SourceEnergyDirectionExponent"   =>  223-1,
        "SourceMeasurmentMantissa"        =>  225-1,
        "SourceMeasurementExponent"       =>  229-1,
        "SourceMeasurmentUnit"            =>  231-1,
        "Unassigned1"                     =>  233-1,
        "Unassigned2"                     =>  237-1)

end
