export bytes_to_samples

"""
Return bytes to samples dict
"""
function bytes_to_samples()

    
    b2s = (
        "TraceNumWithinLine"              =>  1  ,
        "TraceNumWithinFile"              =>  5  ,
        "FieldRecord"                     =>  9  ,
        "TraceNumber"                     =>  13 ,
        "EnergySourcePoint"               =>  17 ,
        "CDP"                             =>  21 ,
        "CDPTrace"                        =>  25 ,
        "TraceIDCode"                     =>  29 ,
        "NSummedTraces"                   =>  31 ,
        "NStackedTraces"                  =>  33 ,
        "DataUse"                         =>  35 ,
        "Offset"                          =>  37 ,
        "RecGroupElevation"               =>  41 ,
        "SourceSurfaceElevation"          =>  45 ,
        "SourceDepth"                     =>  49 ,
        "RecDatumElevation"               =>  53 ,
        "SourceDatumElevation"            =>  57 ,
        "SourceWaterDepth"                =>  61 ,
        "GroupWaterDepth"                 =>  65 ,
        "ElevationScalar"                 =>  69 ,
        "RecSourceScalar"                 =>  71 ,
        "SourceX"                         =>  73 ,
        "SourceY"                         =>  77 ,
        "GroupX"                          =>  81 ,
        "GroupY"                          =>  85 ,
        "CoordUnits"                      =>  89 ,
        "WeatheringVelocity"              =>  91 ,
        "SubWeatheringVelocity"           =>  93 ,
        "UpholeTimeSource"                =>  95 ,
        "UpholeTimeGroup"                 =>  97 ,
        "StaticCorrectionSource"          =>  99 ,
        "StaticCorrectionGroup"           =>  101,
        "TotalStaticApplied"              =>  103,
        "LagTimeA"                        =>  105,
        "LagTimeB"                        =>  107,
        "DelayRecordingTime"              =>  109,
        "MuteTimeStart"                   =>  111,
        "MuteTimeEnd"                     =>  113,
        "ns"                              =>  115,
        "dt"                              =>  117,
        "GainType"                        =>  119,
        "InstrumentGainConstant"          =>  121,
        "InstrumntInitialGain"            =>  123,
        "Correlated"                      =>  125,
        "SweepFrequencyStart"             =>  127,
        "SweepFrequencyEnd"               =>  129,
        "SweepLength"                     =>  131,
        "SweepType"                       =>  133,
        "SweepTraceTaperLengthStart"      =>  135,
        "SweepTraceTaperLengthEnd"        =>  137,
        "TaperType"                       =>  139,
        "AliasFilterFrequency"            =>  141,
        "AliasFilterSlope"                =>  143,
        "NotchFilterFrequency"            =>  145,
        "NotchFilterSlope"                =>  147,
        "LowCutFrequency"                 =>  149,
        "HighCutFrequency"                =>  151,
        "LowCutSlope"                     =>  153,
        "HighCutSlope"                    =>  155,
        "Year"                            =>  157,
        "DayOfYear"                       =>  159,
        "HourOfDay"                       =>  161,
        "MinuteOfHour"                    =>  163,
        "SecondOfMinute"                  =>  165,
        "TimeCode"                        =>  167,
        "TraceWeightingFactor"            =>  169,
        "GeophoneGroupNumberRoll"         =>  171,
        "GeophoneGroupNumberTraceStart"   =>  173,
        "GeophoneGroupNumberTraceEnd"     =>  175,
        "GapSize"                         =>  177,
        "OverTravel"                      =>  179,
        "CDPX"                            =>  181,
        "CDPY"                            =>  185,
        "Inline3D"                        =>  189,
        "Crossline3D"                     =>  193,
        "ShotPoint"                       =>  197,
        "ShotPointScalar"                 =>  201,
        "TraceValueMeasurmentUnit"        =>  203,
        "TransductionConstnatMantissa"    =>  205,
        "TransductionConstantPower"       =>  209,
        "TransductionUnit"                =>  211,
        "TraceIdentifier"                 =>  213,
        "ScalarTraceHeader"               =>  215,
        "SourceType"                      =>  217,
        "SourceEnergyDirectionMantissa"   =>  219,
        "SourceEnergyDirectionExponent"   =>  223,
        "SourceMeasurmentMantissa"        =>  225,
        "SourceMeasurementExponent"       =>  229,
        "SourceMeasurmentUnit"            =>  231,
        "Unassigned1"                     =>  233,
        "Unassigned2"                     =>  237)

    return b2s

end
